name: transacoes_cubos

services:
  backend:
    depends_on:
      - database
    build: .
    ports:
      - 3000:3000
    command: npm run dev
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /cubos_app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: .env
    env_file:
      - .env
    environment:
      DB_HOST: database

  database:
    image: postgres:16
    ports:
      - 5432:${DB_PORT}
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

